### ISSUE TITLE
Undefined variable $nonce in /admin/column.php

### ISSUE THREAD

**Issue by dylankiss** [wimverstuyf/woo-eenvoudigfactureren#2]
Na een van de laatste updates, ik zit nu op Wordpress 5.8.3 en WooCommerce 6.0.0, kan ik geen facturen meer aanmaken via de plugin. Ik krijg in mijn server error log volgende error:

```
[Thu Jan 13 16:22:39.215733 2022] [lsapi:warn] [pid 2340234:tid 140232225617664] [client 178.51.38.86:14057] [host ...] Backend log: PHP Warning:  Undefined variable $nonce in [...]/wp-content/plugins/woo-eenvoudigfactureren-master/admin/column.php on line 45\n, referer: [...]/wp-admin/edit.php?post_status=wc-completed&post_type=shop_order
```

**Comment by wimverstuyf** [comment]
De fout wordt (waarschijnlijk) veroorzaakt door de laatste versie van WordPress.
Een nieuwe versie van de plugin, waar het probleem werd weggewerkt, is beschikbaar.

**Comment by dylankiss** [comment]
[UPDATE] Na het verzenden van een factuur, krijg ik volgde te zien op het "Koppeling" scherm van de EenvoudigFactureren plugin:

`
LAATSTE FOUT: Bestelling #4687: number not unique ({"client_id":11129007,"reference":"Order 4687","layout_id":4919,"tax_included":true,"items":[{"description":"Fonologie in de praktijk - Basistraject - Pre-order \/ Early Bird","amount":111.57,"amount_with_tax":135,"quantity":1,"tax_rate":21,"tax_rate_special_status":"","general_ledger_account":"70410000","stockitem_code":"OLT001-EB"}],"payments":[{"remaining_amount":"yes","method":"online","description":"WooCommerce"}]}) ( 2022-01-15T12:29:58+00:00 )
`

![EenvoudigFactureren_instellingen_‹_Academy_De_Taaltoren_—_WordPress](https://user-images.githubusercontent.com/5985577/149660137-e2702b12-144b-4d2d-977e-29072844f25f.png)

Ik krijg de facturen nog steeds niet gegenereerd. Het enige dat ik nu zie in de logs is het volgende:

```
[Sat Jan 15 13:18:27.547472 2022] [lsapi:warn] [pid 4118116:tid 140265159382784] [client 141.138.168.128:40602] [host ...] Backend log: The is_ajax function is deprecated since version 6.1.0. Replace with wp_doing_ajax.\n, referer: https://[...]/wp-admin/admin-ajax.php?action=as_async_request_queue_runner&nonce=8210169be5
[Sat Jan 15 13:18:29.180658 2022] [lsapi:warn] [pid 4118113:tid 140265494828800] [client 178.51.38.86:6967] [host ...] Backend log: The is_ajax function is deprecated since version 6.1.0. Replace with wp_doing_ajax.\n, referer: https://[...]/wp-admin/edit.php?post_status=wc-completed&post_type=shop_order
```

Maar of dat er iets mee te maken heeft, geen idee ...

**Comment by wimverstuyf** [comment]
De foutmelding in de logs zullen niet gerelateerd zijn.

De nieuwe foutmelding staat los van de plugin. Op basis van de laatst aangemaakte factuur wordt geprobeerd om een factuur met nummer 2022-0023 aan te maken echter bestaat dit factuurnummer reeds (factuur voordien aangemaakt). Om dit op te lossen dient u manueel een factuur aan te maken (bijv. een nulfactuur) met nummer 2022-0024 zodat de nummering opnieuw doorloopt.

**Comment by dylankiss** [comment]
Dat was inderdaad het probleem. Alles werkt weer prima nu. Bedankt voor de hulp!
